export const kitchens = [
  {
    id: 1,
    ownerId: '1',
    name: "Chef's Dream Kitchen",
    location: "Downtown Seattle",
    price: 75,
    rating: 4.8,
    size: 1500,
    imageUrl: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800",
    description: "Modern commercial kitchen with top-of-the-line appliances and ample workspace.",
    amenities: ["Commercial Oven", "Walk-in Freezer", "Prep Station", "Dishwasher"],
    equipment: "Commercial grade appliances, prep stations, storage",
    rules: "Health certification required, Clean after use"
  },
  {
    id: 2,
    ownerId: '2',
    name: "Rustic Home Kitchen",
    location: "Bellevue",
    price: 45,
    rating: 4.5,
    size: 800,
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
    description: "Cozy home kitchen perfect for small catering events and cooking classes.",
    amenities: ["Gas Stove", "Double Oven", "Island Counter", "Basic Utensils"],
    equipment: "Home-style appliances, basic cookware",
    rules: "No late night cooking, Clean as you go"
  },
  {
    id: 3,
    ownerId: '1',
    name: "Industrial Kitchen Space",
    location: "South Lake Union",
    price: 95,
    rating: 4.9,
    size: 2500,
    imageUrl: "https://images.unsplash.com/photo-1556909190-10e7a09a6f1c?w=800",
    description: "Large industrial kitchen suitable for major catering operations.",
    amenities: ["Industrial Equipment", "Loading Dock", "Storage Space", "Multiple Workstations"],
    equipment: "Industrial mixers, ovens, refrigeration",
    rules: "24/7 access, Professional teams only"
  },
  {
    id: 4,
    ownerId: '3',
    name: "Artisan Bakery Kitchen",
    location: "Capitol Hill",
    price: 65,
    rating: 4.7,
    size: 1200,
    imageUrl: "https://images.unsplash.com/photo-1590579491624-f98f36d4c763?w=800",
    description: "Specialized bakery kitchen with stone ovens and pastry stations.",
    amenities: ["Stone Oven", "Proofing Cabinet", "Pastry Station", "Cooling Racks"],
    equipment: "Professional baking equipment, mixers, proofing boxes",
    rules: "Bakery experience required, No night operations"
  },
  {
    id: 5,
    ownerId: '2',
    name: "Asian Fusion Kitchen",
    location: "International District",
    price: 55,
    rating: 4.6,
    size: 1000,
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800",
    description: "Fully equipped kitchen specializing in Asian cuisine with wok stations.",
    amenities: ["Wok Stations", "Rice Cookers", "Steam Tables", "Special Ventilation"],
    equipment: "Commercial woks, steamers, specialized Asian cookware",
    rules: "Experience with Asian cuisine preferred, Proper wok handling required"
  },
  {
    id: 6,
    ownerId: '3',
    name: "Food Truck Prep Kitchen",
    location: "SODO",
    price: 40,
    rating: 4.4,
    size: 600,
    imageUrl: "https://images.unsplash.com/photo-1556911261-6bd341186b2f?w=800",
    description: "Compact but efficient kitchen perfect for food truck prep and storage.",
    amenities: ["Prep Tables", "Storage Units", "Quick-Wash Station", "Loading Area"],
    equipment: "Basic commercial equipment, storage solutions",
    rules: "First come first served, 4-hour minimum booking"
  },
  {
    id: 7,
    ownerId: '1',
    name: "Event Center Kitchen",
    location: "Redmond",
    price: 120,
    rating: 5.0,
    size: 3000,
    imageUrl: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800",
    description: "Massive kitchen facility designed for large events and catering.",
    amenities: ["Multiple Cooking Lines", "Banquet Prep", "Warming Cabinets", "Blast Chiller"],
    equipment: "Full commercial setup, event-specific equipment",
    rules: "Licensed caterers only, Insurance required"
  },
  {
    id: 8,
    ownerId: '2',
    name: "Test Kitchen & Studio",
    location: "Kirkland",
    price: 85,
    rating: 4.8,
    size: 1800,
    imageUrl: "https://images.unsplash.com/photo-1556909190-0d726f1d4f34?w=800",
    description: "Modern kitchen with photography setup for content creation.",
    amenities: ["Photography Lights", "Prep Areas", "Styling Station", "High-End Appliances"],
    equipment: "Camera-ready appliances, photography equipment available",
    rules: "Content creation only, Photo equipment rental available"
  }
]; 